version: '3'

tasks:
  default:
    cmd: task --list-all --sort alphanumeric
    silent: true

  build:
    cmd: cargo build

  clean:
    cmd: cargo clean

  tests:
    cmds:
      - cargo test
      - cargo test --benches

  bench:
    cmd: cargo bench -- --baseline base

  bench-save:
    cmd: cargo bench -- --save-baseline base
