version: '3'

tasks:
  default:
    cmd: task --list-all --sort alphanumeric
    silent: true

  build:
    cmd: cargo build

  clean:
    cmd: cargo clean

  tests:
    cmds:
      - cargo test
      - cargo test --benches

  bench:
    cmd: cargo bench -- --baseline base

  bench-keys:
    cmds:
      - cargo bench boards -- --baseline base
      - cargo bench moves_empty -- --baseline base
      - cargo bench moves_pco -- --baseline base
      - cargo bench moves_center_4_wide -- --baseline base
      - cargo bench moves_randomize -- --baseline base
      - cargo bench can_reach -- --baseline base

  bench-save:
    cmd: cargo bench -- --save-baseline base

  bench-keys-save:
    cmds:
      - cargo bench boards -- --save-baseline base
      - cargo bench moves_empty -- --save-baseline base
      - cargo bench moves_pco -- --save-baseline base
      - cargo bench moves_center_4_wide -- --save-baseline base
      - cargo bench moves_randomize -- --save-baseline base
      - cargo bench can_reach -- --save-baseline base
